### ISSUE TITLE
NullPointerException when running maven update

### ISSUE THREAD

**Issue by jjcard** [jbosstools/jbosstools-fuse#1414]
# New Issue Checklist

## Your Environment

- Windows 7
- Eclipse Photon (though also happened in Oxygen)
- Fuse Tooling for Eclipse 11.0.0.v20180613-2153
- JDK 1.8.0_144 as JavaSE-1.7

## Expected Behaviour

No NullPointerException occurs when running maven update.

## Actual Behaviour

After running Maven->Update Project... would get NullPointerException with the following stacktrace in the logs.

> java.lang.NullPointerException
	at org.fusesource.ide.camel.editor.utils.MavenUtils.isSyndesisExtensionProject(MavenUtils.java:275)
	at org.fusesource.ide.projecttemplates.maven.CamelProjectConfigurator.isValidCamelFacetCandidate(CamelProjectConfigurator.java:323)
	at org.fusesource.ide.projecttemplates.maven.CamelProjectConfigurator.configure(CamelProjectConfigurator.java:89)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:439)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

## Reproduce

It appears its because my pom (which is a child pom, not sure if that matters) does not have a build or plugins blocks. If I add empty ones, it updates fine.

**Comment by apupier** [comment]
@lhein @bfitzpat this is for us in the tooling

**Comment by apupier** [comment]
same issue than https://issues.jboss.org/browse/FUSETOOLS-2944

**Comment by lhein** [comment]
looking at it now

**Comment by lhein** [comment]
provided a PR to fix that problem. thanks for reporting, @jjcard

**Comment by apupier** [comment]
see https://github.com/jbosstools/jbosstools-fuse/pull/1415
